Refactor out configure options into a function

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -26,27 +26,37 @@ install_ruby() {
     # ideally should be using tar with --strip-components 1
     cd $(untar_path $install_type $version $tmp_download_dir)
 
-    if [ "$RUBY_CONFIGURE_OPTIONS" = "" ]; then
-      local configure_options="$(os_based_configure_options) --prefix=$install_path"
 
-      if [ "$RUBY_EXTRA_CONFIGURE_OPTIONS" != "" ]; then
-        configure_options="$configure_options $RUBY_EXTRA_CONFIGURE_OPTIONS"
-      fi
-
-      if [ "$ASDF_PKG_MISSING" != "" ]; then
-        echo "WARNING: Might use OS-provided pkgs for the following: $ASDF_PKG_MISSING"
-      fi
-      unset ASDF_PKG_MISSING #set in os_based_configure_options
-    else
-      local configure_options="$RUBY_CONFIGURE_OPTIONS --prefix=$install_path"
+    if [ "$ASDF_PKG_MISSING" != "" ]; then
+      echo "WARNING: Might use OS-provided pkgs for the following: $ASDF_PKG_MISSING"
     fi
 
-    echo "Building with options: $configure_options"
-    ./configure $configure_options || exit 1
+    local configure_options="$(construct_configure_options)"
+    # set in os_based_configure_options
+    # we unset it here because echo-ing changes the return value of the function
+    unset ASDF_PKG_MISSING
 
+    echo "Building with options: $configure_options"
+
+    ./configure $configure_options || exit 1
     make || exit 1
     make install || exit 1
   )
+}
+
+
+construct_configure_options() {
+  if [ "$RUBY_CONFIGURE_OPTIONS" = "" ]; then
+    local configure_options="$(os_based_configure_options) --prefix=$install_path"
+
+    if [ "$RUBY_EXTRA_CONFIGURE_OPTIONS" != "" ]; then
+      configure_options="$configure_options $RUBY_EXTRA_CONFIGURE_OPTIONS"
+    fi
+  else
+    local configure_options="$RUBY_CONFIGURE_OPTIONS --prefix=$install_path"
+  fi
+
+  echo "$configure_options"
 }
 
 
